swagger: '2.0'
info:
  title: 'Todo Service'
  description: 'API untuk mengatur daftar pekerjaan yg tertunda'
  version: '1.0.0'
  license:
    name: 'GPL-3.0'
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
host: 'localhost'
tags:
  - name: 'todo'
    description: 'endpoint untuk mengubah pekerjaan'
schemes:
  - 'http'
paths:
  /add:
    post:
      tags:
        - 'todo'
      operationId: 'addTask'
      description: 'untuk menambahkan pekerjaan baru'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
        - 'text/plain'
      parameters:
        - in: body
          name: body
          description: informasi tugas
          required: true
          schema:
            $ref: '#/definitions/TaskData'
      responses:
        '200':
          description: 'task yang baru di input'
          schema:
            $ref: '#/definitions/Task'
          examples:
            application/json: { "id": 1, "task": "makan", "done": false }
        '400':
          description: 'data pekerjaan tidak valid'
          examples:
            text/plain: 'data pekerjaan tidak valid'
        '500':
          description: 'kesalahan server'
          examples:
            text/plain: 'kesalahan server'
  /remove:
    post:
      tags:
        - 'todo'
      operationId: 'removeTask'
      description: 'untuk menghapus task lama'
      produces:
        - 'application/json'
        - 'text/plain'
      parameters:
        - in: query
          name: id
          type: integer
          description: id dari task
      responses:
        '200':
          description: 'pekerjaan yang barusan di hapus'
          schema:
            $ref: '#/definitions/Task'
          examples:
            application/json: { "id": 1, "task": "makan", "done": false }
        '401':
          description: 'parameter id tidak ditemukan'
          examples:
            text/plain: 'parameter id tidak ditemukan'
        '404':
          description: 'pekerja tidak ditemukan'
          examples:
            text/plain: 'pekerja tidak ditemukan'
        '500':
          description: 'kesalahan server'
          examples:
            text/plain: 'kesalahan server'
  /list:
    get:
      operationId: 'listTask'
      description: mengembalikan daftar pekerjaan
      tags:
        - 'todo'
      produces:
        - 'application/json'
        - 'text/plain'
      responses:
        '200':
          description: daftar task
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
          examples:
            application/json:
              [
                { "id": 1, "task": "makan", "done": false },
                { "id": 2, "task": "minum", "done": false },
                { "id": 3, "task": "belajar", "done": false }
              ]
        '500':
          description: kesalahan server
          examples:
            text/plain: 'kesalahan server'
  /done:
    put:
      tags:
        - 'todo'
      operationId: 'doneTask'
      description: 'untuk menandakan pekerjaan sudah selesai'
      produces:
        - 'application/json'
        - 'text/plain'
      parameters:
        - in: query
          name: id
          type: integer
          description: id dari task
      responses:
        '200':
          description: 'task yang ditandakan sebagai sudah selesai'
          schema:
            $ref: '#/definitions/Task'
          examples:
            application/json: { "id": 1, "task": "makan", "done": true }
        '401':
          description: 'parameter id tidak ditemukan'
          examples:
            text/plain: 'parameter id tidak ditemukan'
        '404':
          description: 'pekerja tidak ditemukan'
          examples:
            text/plain: 'pekerja tidak ditemukan'
        '500':
          description: 'kesalahan server'
          examples:
            text/plain: 'kesalahan server'
  /undone:
    put:
      tags:
        - 'todo'
      operationId: 'undoneTask'
      description: 'untuk membatalkan penyelesaian sebuah pekerjaan'
      produces:
        - 'application/json'
        - 'text/plain'
      parameters:
        - in: query
          name: id
          type: integer
          description: id dari task
      responses:
        '200':
          description: 'task yang dibatalkan penyelesainnya'
          schema:
            $ref: '#/definitions/Task'
          examples:
            application/json: { "id": 1, "task": "makan", "done": false }
        '401':
          description: 'parameter id tidak ditemukan'
          examples:
            text/plain: 'parameter id tidak ditemukan'
        '404':
          description: 'pekerja tidak ditemukan'
          examples:
            text/plain: 'pekerja tidak ditemukan'
        '500':
          description: 'kesalahan server'
          examples:
            text/plain: 'kesalahan server'

definitions:
  TaskData:
    type: object
    properties:
      task:
        type: string
        description: detail pekerjaan / tugas
        example: makan
  Task:
    type: object
    properties:
      id:
        type: number
        description: identifier pekerjaan
        example: 1
      task:
        type: string
        description: detail pekerjaan / tugas
        example: makan
      done:
        type: boolean
        description: 'true menandakan pekerjaan sudah selesai'
        example: false
